name: CI (Docker)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and test in Docker
        run: |
          docker build -t bt-client .
          docker run --rm bt-client
